name: CI TS
run-name: Проверка CI TS
on: 
  [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-actions
        uses: actions/checkout@v3

      - name: Setup-actions
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: install dependencies
        run: npm ci

      - name: install npm
        run: npm install

      - name: run lint
        run: npm run lint

      - name: run ts
        run: npm run ts
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: linter
    steps:
      - name: echo check
        run: echo 'Echo should work fine :)'