name: Release
run-name: Release
on: [push, workflow_dispatch]
jobs:
  linter:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout-actions
          uses: actions/checkout@v3

        - name: Setup-actions
          uses: actions/setup-node@v3
          with:
            node-version: '16.16.0'
        - name: install dependencies
          run: npm ci

        - name: install npm
          run: npm install

        - name: run lint
          run: npm run lint

        - name: run ts
          run: npm run ts

  release:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - name: 'install dependencies'
        run: npm ci 

      - name: test main
         - env:
            TICKET_ID: ${{ secrets.TICKET_ID }}
            AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
            ORG_ID: ${{ secrets.X_ORG_ID }}
          run: node ./scripts/main.js

  
