name: Release
run-name: Release
on: 
  push:
    tags:
      - "rc-0.0.*"
jobs:
  linter:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout-actions
          uses: actions/checkout@v3

        - name: Setup-actions
          uses: actions/setup-node@v3
          with:
            node-version: '16.16.0'
        - name: install dependencies
          run: npm ci

        - name: install npm
          run: npm install

        - name: run lint
          run: npm run lint

        - name: run ts
          run: npm run ts

  release:
    needs: linter
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/rc-')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - name: 'install dependencies'
        run: npm ci 

      - name: 'update ticket'
        env:
          TAG: ${{ github.ref_name }}
          AUTHOR: ${{ github.actor }}
          TICKET_ID: ${{ secrets.TICKET_ID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          X_ORG_ID: ${{ secrets.X_ORG_ID }}
        run: node ./scripts/updticket.js

      - name: 'build image'
        env:
          TAG: ${{ github.ref_name }}
          TICKET_ID: ${{ secrets.TICKET_ID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          X_ORG_ID: ${{ secrets.X_ORG_ID }}
        run: node ./scripts/image.js
